version: '2'
services:
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web

  web:
    build: .
    container_name: dg01
    command: bash -c "gunicorn web.wsgi -b 0.0.0.0:8000"
    depends_on:
      - db
    volumes:
      - ./src:/src
    expose:
      - "8000"
    environment:
      APP_ENV: 'development'
      APP_DATABASE_PASSWORD: 'p05Tg35'
      APP_STATIC_ROOT: './src/static/'

  db:
    image: postgres:latest
    container_name: ps01
    environment:
      POSTGRES_PASSWORD: 'p05Tg35'

  scrap:
    build: .
    container_name: sc02
    depends_on:
      - db
    volumes:
      - ./src/scraper:/src
    tty: true
    environment:
      APP_DATABASE_PASSWORD: 'p05Tg35'
